### ISSUE TITLE
Immediate todo with new basics help text

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/LD39#10]
Commands:

- [x] look
- [x] power
- [x] realms
- [x] take / get ( see #11 )
- [x] north, west, south, east
- [x] enter (to go to other realms)

**Comment by TangentFoxy** [comment]
- [x] examine / x would also be nice (for looking at WHOSE souls you're grabbing
- [ ] would also be nice to have some dummy characters or NPCs you can kill, since there are likely to be few people on

**Comment by TangentFoxy** [comment]
- [x] health

**Comment by TangentFoxy** [comment]
- [x] exits command,
- [ ] ~~and exit needs to confirm before exiting~~
