### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/LD39#2]
- [x] Call server every second to check for updates.
- [x] ~~Set up htop / DigitalOcean monitoring on third screen.~~
- [x] ~~Set up email password reset.~~
- [x] Alert users when others join.
- [x] `punch`, `say`, ~~`tell`~~ commands. (Tell added to another issue. #12 )
- [x] Ability for server to instruct the terminal to do something (as part of calling the server every second).
- [x] user management: changing passwords, email addresses, usernames
- [x] inventory, looking, other commands

**Comment by TangentFoxy** [comment]
~~URGENTLY NEED TO TELL CLIENT IF OUT OF DATE TO REFRESH.~~ Done.

**Comment by TangentFoxy** [comment]
- [x] ~~Figure out how come I can't get access to internal server errors. How to access them and display appropriate results.~~ Not relevant enough to focus on.

**Comment by TangentFoxy** [comment]
- [x] It might be possible to sign up with "" as your username, fix this.
- [x] It is possible to punch yourself, fix this.
- [x] It is possible to punch a dead body and lower its health. Make it stop lowering its health, and have special message.
- [x] Add `revive` command.
- [x] Add souls to be dropped when you die. And ability to pick them up.

**Comment by TangentFoxy** [comment]
- [x] `look`, `x`, `examine`, `exits`
- [x] ~~ideas.txt had stuff, has stuff, you know, stuff~~ Will look in a bit.
